# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#User.create([
# { :email => "admin@home.com", :password => "password123", :admin? => true },
# { :email => "bigreader@yahoo.com", :password => "password123"},
# { :email => "jackiec@msn.com", :password => "password123"},
# { :email => "alliek@hotmail.com", :password => "password123"},
# { :email => "joeyd@google.com", :password => "password123"},
# { :email => "nlee@rutgers.edu", :password => "password123"},
# { :email => "philm@irs.gov", :password => "password123"},
# { :email => "bigfish@abc.com", :password => "password123"},
# { :email => "frankief@nyu.edu", :password => "password123"},
# { :email => "joannaz@sprint.com", :password => "password123"},
#])

User.create([
 { :email => "admin@home.com", :password => "password123", :admin? => true },
 { :email => Faker::Internet.email, :password => "password123"},
 { :email => Faker::Internet.email, :password => "password123"},
 { :email => Faker::Internet.email, :password => "password123"},
 { :email => Faker::Internet.email, :password => "password123"},
 { :email => Faker::Internet.email, :password => "password123"},
 { :email => Faker::Internet.email, :password => "password123"},
 { :email => Faker::Internet.email, :password => "password123"},
 { :email => Faker::Internet.email, :password => "password123"},
 { :email => Faker::Internet.email, :password => "password123"},
])

UserInfo.create([
 { :name => Faker::Name.name, :city => Faker::Address.city, :state => Faker::Address.state, :user_id => 2},
 { :name => Faker::Name.name, :city => Faker::Address.city, :state => Faker::Address.state, :user_id => 3},
 { :name => Faker::Name.name, :city => Faker::Address.city, :state => Faker::Address.state, :user_id => 4},
 { :name => Faker::Name.name, :city => Faker::Address.city, :state => Faker::Address.state, :user_id => 5},
 { :name => Faker::Name.name, :city => Faker::Address.city, :state => Faker::Address.state, :user_id => 6},
 { :name => Faker::Name.name, :city => Faker::Address.city, :state => Faker::Address.state, :user_id => 7},
 { :name => Faker::Name.name, :city => Faker::Address.city, :state => Faker::Address.state, :user_id => 8},
 { :name => Faker::Name.name, :city => Faker::Address.city, :state => Faker::Address.state, :user_id => 9},
 { :name => Faker::Name.name, :city => Faker::Address.city, :state => Faker::Address.state, :user_id => 10},
])

Book.create([
  { :title => Faker::Book.title, :author => Faker::Book.author, :year => 2009, :fiction => true, :user_id => 3},
  { :title => Faker::Book.title, :author => Faker::Book.author, :year => 2007, :fiction => false, :user_id => 8},
  { :title => Faker::Book.title, :author => Faker::Book.author, :year => 2014, :fiction => true, :user_id => 5},
  { :title => Faker::Book.title, :author => Faker::Book.author, :year => 2011, :fiction => true, :user_id => 2},
  { :title => Faker::Book.title, :author => Faker::Book.author, :year => 2014, :fiction => false, :user_id => 10},
  { :title => Faker::Book.title, :author => Faker::Book.author, :year => 2010, :fiction => false, :user_id => 10},
  { :title => Faker::Book.title, :author => Faker::Book.author, :year => 1998, :fiction => false, :user_id => 4},
  { :title => Faker::Book.title, :author => Faker::Book.author, :year => 2011, :fiction => true, :user_id => 3},
  { :title => Faker::Book.title, :author => Faker::Book.author, :year => 2014, :fiction => true, :user_id => 7},
  { :title => Faker::Book.title, :author => Faker::Book.author, :year => 1996, :fiction => true, :user_id => 4},
])

Review.create([
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 1, :user_id => 2, :book_id => 1},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 2, :user_id => 2, :book_id => 2},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 3, :user_id => 2, :book_id => 3},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 4, :user_id => 2, :book_id => 4},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 5, :user_id => 2, :book_id => 5},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 5, :user_id => 3, :book_id => 6},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 4, :user_id => 3, :book_id => 7},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 3, :user_id => 3, :book_id => 8},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 2, :user_id => 3, :book_id => 9},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 1, :user_id => 3, :book_id => 10},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 1, :user_id => 4, :book_id => 1},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 2, :user_id => 4, :book_id => 3},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 3, :user_id => 4, :book_id => 5},
  { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 4, :user_id => 4, :book_id => 7},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 5, :user_id => 4, :book_id => 9},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 5, :user_id => 5, :book_id => 2},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 4, :user_id => 5, :book_id => 4},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 3, :user_id => 5, :book_id => 6},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 2, :user_id => 5, :book_id => 8},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 1, :user_id => 5, :book_id => 10},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 1, :user_id => 6, :book_id => 1},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 2, :user_id => 6, :book_id => 2},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 3, :user_id => 6, :book_id => 3},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 4, :user_id => 6, :book_id => 9},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 5, :user_id => 6, :book_id => 10},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 5, :user_id => 6, :book_id => 4},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 4, :user_id => 6, :book_id => 5},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 3, :user_id => 6, :book_id => 6},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 2, :user_id => 6, :book_id => 7},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 1, :user_id => 6, :book_id => 8},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 1, :user_id => 7, :book_id => 1},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 2, :user_id => 7, :book_id => 2},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 3, :user_id => 7, :book_id => 3},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 4, :user_id => 7, :book_id => 4},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 5, :user_id => 7, :book_id => 5},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 5, :user_id => 8, :book_id => 6},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 4, :user_id => 8, :book_id => 7},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 3, :user_id => 8, :book_id => 8},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 2, :user_id => 8, :book_id => 9},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 1, :user_id => 8, :book_id => 10},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 1, :user_id => 9, :book_id => 1},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 2, :user_id => 9, :book_id => 3},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 3, :user_id => 9, :book_id => 5},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 4, :user_id => 9, :book_id => 7},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 5, :user_id => 9, :book_id => 9},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 5, :user_id => 10, :book_id => 2},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 4, :user_id => 10, :book_id => 4},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 3, :user_id => 10, :book_id => 6},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 2, :user_id => 10, :book_id => 8},
 { :summary => Faker::Lorem.sentence, :body => Faker::Lorem.paragraph(rand(5..20)), :rating => 1, :user_id => 10, :book_id => 10},
])